# Generated by Django 3.1.7 on 2021-03-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_field',
            new_name='image',
        ),
    ]
